import React,{useEffect,useRef,useState}from'react';import{createRoot}from'react-dom/client';import gsap from'gsap';import{ScrollTrigger}from'gsap/ScrollTrigger';import Lenis from'lenis';import'./styles.css';gsap.registerPlugin(ScrollTrigger);
const posts=[{id:'DVSdxs5ko46',kind:'reel',title:'The food run'},{id:'DVm_IH5CSr_',kind:'p',title:'After dark'},{id:'DVnAs5Hjqgr',kind:'p',title:'Berbuka at Merdeka'}];
const cats={MAINS:['Nasi & lauk','Rice bowls','Local favourites'],GRILL:['Satay','Ayam percik','Charcoal grill'],DRINKS:['Air balang','Coffee','Cold drinks'],DESSERTS:['Kuih','ABC','Sweet things']};
function IG({p}){return <div className="ig"><iframe title={p.title} src={`https://www.instagram.com/${p.kind}/${p.id}/embed/`} loading="lazy" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"/></div>}
function App(){const root=useRef(null),[cat,setCat]=useState('MAINS');useEffect(()=>{const lenis=new Lenis({duration:1.15,smoothWheel:true});lenis.on('scroll',ScrollTrigger.update);let r;function loop(t){lenis.raf(t);r=requestAnimationFrame(loop)}r=requestAnimationFrame(loop);const ctx=gsap.context(()=>{gsap.from('.hero-copy>*',{y:28,opacity:0,duration:1.05,stagger:.1,ease:'power3.out'});gsap.utils.toArray('.reveal').forEach(el=>gsap.from(el,{y:35,opacity:0,duration:.9,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 86%'}}));gsap.timeline({scrollTrigger:{trigger:'.senja',start:'top top',end:'bottom bottom',scrub:1.2}}).to('.senja-scene',{backgroundColor:'#a8755d'},.05).to('.senja-scene',{backgroundColor:'#59616a'},.38).to('.senja-scene',{backgroundColor:'#25333a'},.7).to('.senja-scene',{backgroundColor:'#172126'},1).to('.sun',{y:'46vh',opacity:0},0).to('.glow',{opacity:1},.55).to('.time-a',{opacity:0},.18).to('.time-b',{opacity:1},.3).to('.time-b',{opacity:0},.62).to('.time-c',{opacity:1},.7);},root);return()=>{cancelAnimationFrame(r);ctx.revert();lenis.destroy()}},[]);return <main ref={root}>
<nav><a className="logo" href="#top">BAZRAM <i>MERDEKA</i></a><div><a href="#stories">Stories</a><a href="#makan">Makan</a><a href="#plan">Plan</a></div><a href="#visit">Visit ↗</a></nav>
<section className="hero" id="top"><div className="hero-media"><IG p={posts[0]}/><div className="veil"/></div><div className="hero-copy"><span>RAMADAN · STADIUM MERDEKA · KUALA LUMPUR</span><h1>BAZRAM<br/><em>MERDEKA</em></h1><p>A Ramadan gathering built around food, community and one of Kuala Lumpur’s most iconic spaces.</p><div className="essentials"><b>21 FEB — 18 MAC</b><b>4PM — 11PM</b><b>100+ VENDORS</b></div></div></section>
<section className="overview reveal"><header><span>01 / THE GATHERING</span><h2>One field.<br/>A whole evening.</h2></header><div className="facts">{[['100+','food & drink vendors'],['01','historic stadium'],['IFTAR','picnic on the field'],['NIGHT','KL after dark']].map(x=><article><strong>{x[0]}</strong><p>{x[1]}</p></article>)}</div></section>
<section className="stories" id="stories"><div className="section-head reveal"><span>02 / STORIES FROM MERDEKA</span><h2>The night,<br/><em>as it happened.</em></h2><p>Real moments from Bazram. Food, people and the stadium after sunset.</p></div><div className="story-grid"><div className="feature reveal"><IG p={posts[0]}/><small>THE FOOD RUN · @BAZRAMMERDEKA</small></div><div className="support reveal"><IG p={posts[1]}/><IG p={posts[2]}/></div></div></section>
<section className="makan" id="makan"><div className="section-head reveal"><span>03 / MAKAN</span><h2>Nak makan<br/><em>apa?</em></h2><p>Start with what you are craving. Keep the decision simple.</p></div><div className="tabs">{Object.keys(cats).map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="choices">{cats[cat].map((x,i)=><article><span>0{i+1}</span><h3>{x}</h3><p>{['Crowd favourites and filling plates.','Fresh from the heat. Follow the smoke.','Easy to carry across the field.'][i]}</p></article>)}</div></section>
<section className="senja"><div className="senja-scene"><div className="sun"/><div className="architecture"><i/><i/><i/><i/><i/></div><div className="field-line"/><div className="glow">{Array.from({length:12}).map((_,i)=><i key={i}/>)}</div><div className="senja-copy"><span>04 / THE SHIFT</span><h2>FROM SENJA<br/><em>TO MALAM.</em></h2><p className="time time-a">5:40 PM · warm concrete, long shadows</p><p className="time time-b">7:05 PM · first lights across the field</p><p className="time time-c">8:00 PM · Stadium Merdeka after dark</p></div></div></section>
<section className="plan" id="plan"><div className="section-head reveal"><span>05 / PLAN YOUR NIGHT</span><h2>Arrive easy.<br/><em>Stay awhile.</em></h2></div><div className="plan-grid reveal"><div className="schedule">{[['4:00','Gates open'],['5:30','Peak food browsing'],['7:20','Prepare for iftar'],['7:30','Communal iftar'],['8:15','Bazram after dark']].map(x=><div><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><div className="map"><div className="stadium">IFTAR FIELD</div>{['HOT FOOD','DRINKS','PICNIC','PRAYER'].map((x,i)=><span className={'pin p'+i}>{x}</span>)}</div></div></section>
<section className="visit" id="visit"><span>06 / VISIT</span><h2>COME TO<br/><em>MERDEKA.</em></h2><div><p>Stadium Merdeka<br/>Kuala Lumpur</p><p>Daily during Bazram<br/>4PM — 11PM</p><p>Public transport<br/>recommended</p></div><a href="https://www.instagram.com/bazrammerdeka/" target="_blank" rel="noreferrer">FOLLOW @BAZRAMMERDEKA ↗</a></section>
</main>}createRoot(document.getElementById('root')).render(<App/>);